services:
  intern:
    container_name: intern
    image: chokyuseong/intern:latest
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=docker